### ISSUE TITLE
Validate the second moment calculation

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#16]
Commented out everything and coded again

**Comment by jennykim1016** [comment]
Unit test done!

**Comment by drphilmarshall** [comment]
Good stuff - I see it, in `tests`. It takes a longtime to run, though - you
want your unit tests to run in a few seconds or less. Maybe only paint a
small sample of galaxies in the test case?

**Comment by jennykim1016** [comment]
I am not entirely sure whether I understood correctly, but the unit tests are in `test_SLRealizer.py`, which could be found under the branches such as `obs_err`. If I write a command `nosetests` and execute in terminal, it takes around 1-2 seconds to finish. I think I am not painting any galaxies in the code, because I just wanted to test whether I get the numerical values correct. Would unit-testing the plots be helpful (or, would we use the plots later)? Thanks!

**Comment by drphilmarshall** [comment]
OK, maybe it's just your master branch then - there, the tests take about a
minute.

Regarding unit testing plotting code: I tend to do this from the notebook
I'm working in, since the "test" for a plot is whether it looks right...
