### ISSUE TITLE
Set up unittests framework

### ISSUE THREAD

**Issue by mbaumer** [jennykim1016/SLRealizer#24]
We need the unittests framework to create and run tests for our code. Let's follow the example of OM10 in setting it up: https://github.com/drphilmarshall/OM10/tree/master/tests

**Comment by mbaumer** [comment]
Here are the docs for the `unittest` package: https://docs.python.org/2/library/unittest.html

**Comment by jennykim1016** [comment]
Done! :)

**Comment by drphilmarshall** [comment]
Bravo! :-)
