### ISSUE TITLE
Items for this week

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#30]
- [x] It should based on a realistic LSST selection of OM10 lensed quasars i.e. ~ 1000 lenses or whatever the standard LSST selection is
_There are 3000 + LSST-like selections avaliable_
- [x] It should assume a null deblender, that leads to a single Source being cataloged at each visit epoch
- [x] The visit sequence will be that provided by Rahul in the "ObservingHistory" notebook
- [x] It should make reasonable assumptions about the observational errors
- [x] It should be stored as a csv format file that can be read in with Pandas
- [x] It should contain columns as follows: MJD, filter, ra, ra_err, dec, dec_err, flux, flux_err, qxx, qxx_err, qyy, qyy_err, qxy, qxy_err, psf_sigma, sky

_I did: MJD, filter, x, x_err, y, y_err, flux, flux_err, qxx, qxx_err, qyy, qyy_err, qxy, qxy_err, psf_sigma, sky, lensID_

- [x] The same assumed filter set and magnitude zero point as painted OM10

_ I think because we used SDSS filters, we should use SDSS zeropoints when calculating the flux. It would be helpful to check once again though! _
_ http://www.sdss.org/dr12/algorithms/magnitudes/#nmgy _

**Comment by drphilmarshall** [comment]
Good! If I were you I'd add separate columns for `ra` and `dec` - its the
`x` and `y` that you mainly need, for moment calculations.

**Comment by jennykim1016** [comment]
Oh, I see! I will fix that. Thank you so much!! :) 

So the followings are the items that I haven't done yet:

- [x] Add RA and DEC columns. Refer to the code that om10 has which converts x and y offsets in arcsec into RA and DEC. Take a small random number (+/- 1 degree) from the observation history field center. The values might be (RA, Dec) = (03:32:30, 10:00:24). Be aware of the coordinate conversions!

edit ) _there is also another way to calculate the offsets : https://github.com/astropy/astropy/issues/4209_
edit 2 ) _OM 10 method that I should refer to is : make_sim_input_catalog_

- [x] Clean the code and ask for a code review

**Comment by jennykim1016** [comment]
For RA and DEC, this is what I currently understood from the previous advice:

1) we know x and y 1st moment, so convert that to offset in RA and DEC and add to the known RA, DEC values
2) draw random number (-1 - +1 deg) and also add that to 1)

I should think about this more tomorrow, but I think I can start from here. You will have a great Monday!! :)

**Comment by jennykim1016** [comment]
This closes #16 #17 and #29!

**Comment by drphilmarshall** [comment]
Good good! I think only #16 will get closed by that message, the "closes"
only works for one issue at a time.

BTW regarding object positions, I think:
* You should generate a true lens galaxy sky position by a degree-scale
random offset from the obs history field center
* Then you should generate true lensed QSO image positions by adding on the
relevant x and y offsets (in RA and Dec degrees!)
* Then, to make a mock observed catalog, you should apply the Null
Deblender to get a single object position in each filter, and then draw
small random observational offsets from the model astrometric error
distribution and apply them to x and y, and the same ones to RA and Dec to
get mock observed x, y, RA, Dec

Do you agree? Does this emulate noisy measured object positions in the
right way?

**Comment by mbaumer** [comment]
We are thinking that for small offsets like we have, the flat sky approximation should still be good, so instead of the order you suggest of 1. Paste lens onto sky, 2. paste lensed images onto sky, 3. deblend, we are thinking that 1. Pasted lensed images onto len galaxy at (0,0), 2. Deblend, 3. Add RA, DEC offsets to locate on sky should give the same results. This is what the code does now. Sound good?

**Comment by jennykim1016** [comment]
Close #29 -- already did
