### ISSUE TITLE
Cornerplots of catalog quantities

### ISSUE THREAD

**Issue by mbaumer** [jennykim1016/SLRealizer#32]
Hi Jenny! Once you have made an LSST mock catalog for ~1000 lens systems, a good thing to do for Thursday would be to make a notebook with corner* plots of the measured quantities. I think the most interesting ones will be fluxes and second moments in the different filter bands, as well as differences between them. 

A default set to make would be:
1. MAG_I, MAG_U-MAG_G, MAG_G-MAG_R, MAG_R-MAG_I, MAG_I-MAG_Z, MAG_Z-MAG_Y
2. 2NDMOM_U, 2NDMOM_G, 2NDMOM_R, 2NDMOM_I, 2NDMOM_Z, 2NDMOM_Y

You might also construct size and ellipticity estimates from the 2nd moments, using:

size = I_xx + I_yy
e1 = (I_xx - I_yy)/size
e2 = (2*I_xy)/size

*See documentation for the "corner" package at:
https://corner.readthedocs.io/en/latest/pages/quickstart.html

**Comment by jennykim1016** [comment]
Hi Mike,

I was working on generating the cornerplot, but I was not sure about one point. 

For now, I generate the catalog by

1) randomly selecting N lenses from 3000 LSST-like systems (N is passed by users)
2) then, for each of N lenses, I randomly select one epoch(epochs have different filters, seeings, and MJD) from the `observation.csv` file.

Thus, the catalog has columns: ['MJD', 'filter', 'RA', 'RA_err', 'DEC', 'DEC_err', 'x', 'x_com_err', 'y', 'y_com_err', 'flux', 'flux_err', 'qxx', 'qxx_err', 'qyy', 'qyy_err', 'qxy', 'qxy_err', 'psf_sigma', 'sky', 'lensid']

The problem with this is that 1) the seeing between lenses would be different and 2) most of the lenses would not have full RUGIZ moments. Most of them will have one or two band moments, but that would not be enough for the cornerplot, especially for the first one where we have to know the color index for each lens.

Thus I am thinking of making another wrapper method which chooses five different epoch with different filters(RUGIZ) and loop through the whole lenses to calculate the full moments. This will guarantee that the seeing across the same band will be the same, and all the lenses will have RUGIZ moments. Would you think it is a good style?

Thank you so much!

**Comment by jennykim1016** [comment]
Already got answers from Thursday meeting, closing the issue :)
