### ISSUE TITLE
rename corner.py

### ISSUE THREAD

**Issue by mbaumer** [jennykim1016/SLRealizer#38]
Hi Jenny,
Can you rename your corner.py to something else? It makes it so that when you invoke `import corner` it loads your plotting code, rather than the actual cornerplotting package.
Thanks!
Mike

**Comment by jennykim1016** [comment]
Oh, I do not need that file. I will delete it right now, sorry about it!

**Comment by jennykim1016** [comment]
I deleted from both `obs_err_ext` branch and `corner_cat` branch :) I think the other branches do not have that file.

**Comment by mbaumer** [comment]
Thanks!

**Comment by jennykim1016** [comment]
No problem!! :D
