### ISSUE TITLE
Dropbox link for the object table - rename needed

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#41]
https://www.dropbox.com/s/21f0wgaewse1lgy/source_table.csv?dl=0

**Comment by drphilmarshall** [comment]
Looks promising, but some tweaks needed - see below. What are the fields
that start with eg `g_x_com_` and have values ~1e-6?

* You need columns for the OM10 lens `id`, visit `mjd`, and visit `filter`
- because a "source" is a detection of an object (labelled by `id`) in a
given observation (that has an `mjd` date and was taken in some `filter`).

* This means that the columns should just be eg `x` and not `g_x` (because
the filter information is in the `filter` column)

**Comment by jennykim1016** [comment]
Hi @drphilmarshall ,

I think I made the confusion by naming the object file a "source file". Sorry about this! The one linked above is actually the object catalog. The real catalogs are as follows. I used 200 lensed system and 200 different observation epochs.

source table: https://www.dropbox.com/s/gwv4fzxl6s6mvr5/source_table.csv?dl=0
object table (averaging sources per filter, previously named as a "source_table" ): https://www.dropbox.com/s/21f0wgaewse1lgy/object_table.csv?dl=0

**Comment by drphilmarshall** [comment]
Ah! OK, good - that makes more sense. You still need the `lensid` in the
Object table though, to allow the tables to be joined. One last thought:
its only for convenience that we are writing the sky level (5-sigma depth)
into the source table. You could also define a "visit table" that just
lists sky, PSFsize, filter and MJD - which would just be the observation
history you have. It's up to you which way you do it but if you like
keeping the sky level with the source measurements, you shoudl also put the
PSF size in there too.

**Comment by jennykim1016** [comment]
Hi @drphilmarshall ,

Yeah, I also think it does not make sense to drop `lensid` in the object table. I fixed the code! :) 
For the source table, I think in the previous file, I put both PSF and sky values. Would it be better to get rid of both two? I think making a visit table would not add anything because it would just be the observation history as you mentioned.

Thanks!

**Comment by drphilmarshall** [comment]
I guess you can keep the PSF width and sky in with the sources for now,
they won't add much to the file size (especially if its compressed). Sorry,
I missed that you had teh PSF size in there! Good good.

**Comment by jennykim1016** [comment]
Thank you!! I will delete the columns eventually when I add more rows. See you tomorrow!
