### ISSUE TITLE
Unit for the center of moment?

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#44]
Hi @mbaumer ,

I was re-checking the unit for the x_com and y_com for the cornerplot, and I think those are in arcseconds. I am 80% convinced about my reasonings, but could you double-check whether it makes sense? My justifications are as follows.

I made a 2D array that ranges from (-5, 5) for both x and y.Then, I put the OM10 lensing galaxy at (0, 0), and I added lensed images on the position based on their offsets to the lensing galaxy (this value is given in the OM10 catalog). Then, I null-deblended the image and calculate the position of the COM on that array. Here, because OM10 catalog's offsets and 2D array's axis are in arcsec units, not pixel or degrees, the computed first moment should also has arcsecs as its units.

Are there anything that I am not taking account of? Thank you so much!

**Comment by mbaumer** [comment]
Hi Jenny,
When you say the grid is (5,5), how many pixels does this grid have? If
each pixel has a size of 1 arcsecond, then your reasoning is correct, but
if your grid with range (-5,5) has, say 100 pixels, then each pixel is only
.1" across. When you compute the moment on these pixels, the moment will be
computed in pixel units (in this case .1").
LSST will have a pixel size of .2"/pixel, so perhaps this is a good value
to use.

**Comment by jennykim1016** [comment]
Thank you so much! My grid of range (-5, 5) has 100 pixels, but I will change the numbers so that the pixel size will match with that of LSST :)
