### ISSUE TITLE
Assumptions + Hacks

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#50]
- Both `REFF` and `REFF_T` is zero in OM10 lenses. This means we are going to assume that all the lenses and quasars are point sources.
- #49 We are eliminating the lenses which have ellipticity greater than 0.5. There are 2813 LSST-like lenses, and 297 lenses have ellipticity greater than 0.5.
- Adding noise give weird HSM error (findAdaptiveMoment() no longer converges). Before I fix it, I will manually add noise

**Comment by mbaumer** [comment]
Hi Jenny,
If adding noise to the images is causing problems, just ignore it for
now--in fact, as a test of our code, we should make sure that the
"perfect", noise-free results make sense!

**Comment by jennykim1016** [comment]
Hi Mike, 

Thank you so much! There are a few different cases like `findAdaptiveMoment()` doesn't converge or `adaptiveMoment()` has `NaN` so it seemed really hard to debug. I was just generating random numbers as we did before (i.e. 5% for the second moment) and add those to the real values, but would it be better to just use the pure, perfect values returned by `findAdaptiveMoment()` without adding any noises manually?
