### ISSUE TITLE
ML Progress

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#56]
Step 1. Extract useful features:
- I chose $e_u-e_z$, $e_g-e_z$, $e_r-e_z$, $e_i-e_z$, $e_u$, $e_g$, $e_r$, $e_i$, $e_z$, $\Sum e$, first_moment_y for each filter, first_moment_x for each filter, first_moment_y - first_moment_x for each filter, umag-zmag, umag-imag, zmag-gmag, umag-gmag, imag-zmag, rmag-imag, gmag-rmag. I will later add size, but for now, I didnt't include size. The feature extraction was based on the cornerplot that I drew in `origin/noise_generate`

I checked the constants again, and there were actually ~500 LSST-like samples. 3000 is when we include area = 15000-20000.

Step 2. Divide the feature catalog into the training and testing set.
33% of the sample will be the testing set, and 67% of the sample will be the training set.

Step 3. Try different algorithms with different initial setting - choosing algorithms based on the sklearn cheat sheet
- LinearSVC (I do not have to set any numbers)
![linearsvc](https://user-images.githubusercontent.com/18297066/29479330-569ac768-8426-11e7-94c9-22bd7e073f61.png)

- Nearest Neighbors (variable N)
     - N = 3
 ![g](https://user-images.githubusercontent.com/18297066/29480759-9daed690-842f-11e7-97b0-8220aad216a9.png)

     -  N = 10
![b](https://user-images.githubusercontent.com/18297066/29480733-5e54c02c-842f-11e7-94f3-c8c986391a53.png)

 - Random Forest (variable N)

      - N = 3
![e](https://user-images.githubusercontent.com/18297066/29480744-71f4f976-842f-11e7-8a69-1e56d63b2d25.png)

      - N = 5
![d](https://user-images.githubusercontent.com/18297066/29480747-78215380-842f-11e7-96ae-d5a2108c7583.png)

      - N = 10
![c](https://user-images.githubusercontent.com/18297066/29480748-7d55b9e0-842f-11e7-9507-1021e5896bda.png)

It will look much better if I can merge these graphs into one, but my version of jupyter somehow doesn't allow this..... I will run in a different computer later.

**Comment by jennykim1016** [comment]
Just merged! Probability for overfitting increases : LinearSVC < NearestNeighbors < RFs. Random Forest had the best recall given a precision for all values. 

![merged](https://user-images.githubusercontent.com/18297066/29480961-6f6b2886-8431-11e7-81cd-c2491494cb84.png)

**Comment by mbaumer** [comment]
Hi Jenny,
This looks great! Enjoy the eclipse, and we can discuss other
tests/improvements to these methods when you get back.
Mike

**Comment by jennykim1016** [comment]
Thank you! Have a nice weekend!! :)
