### ISSUE TITLE
Plans for this week

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#59]
- [x] finish designing the poster
       - make the u-z and g-z cornerplot
       - dont forget to add the ranges into the cornerplot
       - run with 3,000 lenses with first three years of observation
- [x] ellipticity bug?
       - investigate by :
1) just realizing galaxies 
2) taking out lens galaxies 
![image](https://user-images.githubusercontent.com/18297066/29734744-d07e8628-89a8-11e7-9f75-1984175b0e1b.png)
^ This is the ellipticity of 3,000 lensed system without galaxies. The peak in ellipticity of the lensed system is actually greater than the peak in ellipticity of the SDSS.
3) add size

- [x] total flux cut - make a weak cut but cut based on the realized flux
 : 2323 samples, no need to make a weak cut!
- [x] good object table with better seeing. better features
- [x] clean up the directory!!! PLEASE COMMENT THE CODE I AM FORGETTING WHAT I HAVE BEEN DOING

**Comment by mbaumer** [comment]
Hi Jenny,
This is good that the lensed images (without the lens galaxy) have a large ellipticity -- it shows they are contributing *something* to the ellipticity at least, even if in the end they are overwhelmed by the lens galaxy. 

Great job getting to a 3000 lens sample! I would focus on your first item (making the u-z and g-z feature cornerplots), as well as figuring out why the ROC curve you made has so few points. Those two items are key elements of your poster!
Mike

**Comment by jennykim1016** [comment]
Done with the items :) Closing the issue
